backend:
  name: git-gateway
  branch: main  # Use your correct branch name

media_folder: "uploads" # Folder for images
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
